### ISSUE TITLE
SE300 does not comply with the CERN OHL 1.2 that the SmartEffector was licensed under.

### ISSUE THREAD

**Issue by thantik** [seemecnc/Machine_Elements#4]
GBR files are, essentially, 'compiled' versions of hardware that cannot be edited directly.  It is in violation of Section 3.4, subsection D.  Would you please post the kicad source files of this modified effector?

**Comment by PartDaddy** [comment]
The text file "license information.txt" provides reference back to source

**Comment by thantik** [comment]
You must _"make available **the modified Documentation at the same level of abstraction as that of the Documentation, in the preferred format for making modifications to it** (e.g. the native format of the CAD tool as applicable), and in the event that format is proprietary, in a format viewable with a tool licensed under an OSI-approved license if the proprietary tool can create it"_

Reference back to the original does not comply with this license.  You must release source files of your modified variant to comply with the license.

**Comment by PartDaddy** [comment]
well I'll put this on my list of todo's, I use diptrace, so I'll get those
up. I have no idea what export options there are let alone anything about
kicad (tried that, but it is really not intuitive)
